export {
  deriveBookId,
  deriveChapterId,
  EpubIngestionAdapter,
  type EpubIngestionAdapterOptions,
  EpubIngestionError,
  type EpubIngestionErrorCode,
  type EpubIngestionMapper,
  type EpubUpload,
  type ExclusionClassification,
  INGESTION_SCHEMA_VERSION,
  type IngestedChapter,
  type IngestedChapterHeading,
  type IngestedSourcePassage,
  type IngestedTitleSource,
  type IngestionAudit,
  type NonStorySpineDocument,
  type StorageCommitPoint,
  type StoredCover,
  type StoredEpubIngestion,
  type StoredUploadProvenance,
  type TextExclusionAudit,
} from './adapter.js'
export {
  type BookLockCoordinator,
  BookLockError,
  type BookLockErrorCode,
  FileBookLockCoordinator,
  type FileBookLockCoordinatorConfig,
  type HeldBookLock,
} from './book-lock.js'
export {
  DOMAIN_EPUB_EXTRACTOR_IDENTITY,
  DOMAIN_EPUB_EXTRACTOR_SETTINGS,
  DomainBookMapper,
  DomainEpubExtractor,
} from './domain-mapper.js'
export {
  DEFAULT_EPUB_XML_LIMITS,
  type DeterministicEpubExtraction,
  deriveSourcePassageId,
  type EpubSpikeExtraction,
  type EpubXmlLimits,
  EXTRACTION_IDENTITY,
  type ExtractedCover,
  type ExtractedSpineDocument,
  type ExtractionFinding,
  type ExtractionIdentity,
  extractEpubDeterministically,
  extractEpubForSpike,
  type ImageOccurrence,
  type NavigationEvidence,
  type NavigationSourceEvidence,
  type NavigationSourceStatus,
  OFFSET_UNIT,
  type PublicationContributor,
  type PublicationMetadata,
  type PublicationTitle,
  type SourceAnnotation,
  type SourcePassageRecord,
  type TextLedgerEntry,
} from './extractor.js'
export {
  DEFAULT_EPUB_ARCHIVE_LIMITS,
  type EpubArchiveLimits,
  unzipEpubSafely,
} from './safe-zip.js'
